### ISSUE TITLE
Page 115: Sorting doesn't work unless template is updated

### ISSUE THREAD

**Issue by bbonamin** [abuiles/ember-cli-101-errata#109]
Hi,

On Page 115, you specify how to use `sortProperties` and `sortAscending` to sort the friends list.
It was not working for me, until I changed the `friends/index.hbs` template from:

``` handlebars
<tbody>
    {{#each friend in model}}
    <tr>
```

to

``` handlebars
<tbody>
    {{#each friend in controller}}
    <tr>
```

You also show the template on Page 116 as `{{#each friend in model}}`, so perhaps it should be changed there too? 

Honestly I'm a newbie in EmberJS so I don't know if this is an Ember deprecation or something that wasn't noticed before. For the record, I'm using `ember-cli 0.1.4` and:

```
"DEBUG: -------------------------------" vendor.js:28547
"DEBUG: Ember      : 1.8.1" vendor.js:28547
"DEBUG: Ember Data : 1.0.0-beta.12" vendor.js:28547
"DEBUG: Handlebars : 1.3.0" vendor.js:28547
"DEBUG: jQuery     : 1.11.1" vendor.js:28547
"DEBUG: -------------------------------"
```

**Comment by stevenharman** [comment]
Yep, I just hit this too. Granted, I'm using Ember 1.9.0, so perhaps there's been a change between 1.7 (which the book is based on, I believe?) and now.

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.9.0
DEBUG: Ember Data : 1.0.0-beta.12
DEBUG: Handlebars : 2.0.0
DEBUG: jQuery     : 1.11.2
DEBUG: -------------------------------
```

**Comment by vais** [comment]
@abuiles is this a bug in ember? I was under the impression that `model` and `controller` are pretty much interchangeable. In this case, `{{#each friend in model}}` does not work, but `{{#each friend in controller}}` works.

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.8.1
DEBUG: Ember Data : 1.0.0-beta.12
DEBUG: Handlebars : 1.3.0
DEBUG: jQuery     : 1.11.2
DEBUG: -------------------------------
```

EDIT: either way, this should probably get fixed in the book - I only figured out how to make it work thanks to this issue filed by @bbonamin

**Comment by sirneb** [comment]
Models and controllers are actually quite different.  I think it's easiest to think of controllers as decorated models while models are anything you define in the model object(ie. app/models/friend.js).  So "fullName" is a model property which is in both models and controllers but the sortable properties are in the controller since that's only defined there.

When we access "model" in the template, we are implicitly calling "this.model" and "this" is the controller.  We can easily see this for ourselves if we put {{debugger}} in our templates.

**Comment by abuiles** [comment]
I have rework this part to not use the ArrayController any more so that should clear the confusion :). It will be available on the next release with info about the change.
