### ISSUE TITLE
Page 75: Activate and Deactivate hooks

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#61]
Wouldn't it be just as convenient to take these actions in the controller at the exact place where cancel or save is being done?

Keep similar related code together and not spread out which makes it harder for maintenance later on?

What is the justification for moving this to the route?

**Comment by abuiles** [comment]
The deactivate and resetController hooks are there exactly for this, also if we do this on the save and cancel action, then it won't work all the time because you can navigate out of that route clicking on a link to other route for example, in that scenario none of the actions will be called while the route hooks will.

**Comment by kgish** [comment]
Okay that makes sense, didn't think about that ...
